### ISSUE TITLE
Sender: InvalidParameterValue

### ISSUE THREAD

**Issue by suvozit** [RimeOfficial/postmaster#19]
```
An Error Was Encountered

Array
(
 [message] => getAwsRequestId: fb1aa6a8-27f4-11e6-9363-b55f4c4e4535, getAwsErrorType:client, getAwsErrorCode:InvalidParameterValue

Error executing "SendRawEmail" on "https://email.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://email.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:

 
 Sender
 InvalidPara (truncated...)
 InvalidParameterValue (client): Missing '"' - 
 
 Sender
 InvalidParameterValue
 Missing '"'
 
 fb1aa6a8-27f4-11e6-9363-b55f4c4e4535


#0 /srv/www/postmaster/releases/20160601115602/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(76): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command))
#1 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\WrappedHttpHandler->Aws\{closure}(Array)
#2 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/Promise.php(174): GuzzleHttp\Promise\Promise::callHandler(2, Array, Array)
#3 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/RejectedPromise.php(40): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array)
#4 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#5 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#6 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/Promise.php(266): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#13 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#14 /srv/www/postmaster/releases/20160601115602/vendor/guzzlehttp/promises/src/functions.php(197): GuzzleHttp\Promise\Promise->wait()
#15 /srv/www/postmaster/releases/20160601115602/application/libraries/Lib_archive.php(67): GuzzleHttp\Promise\unwrap(Array)
#16 /srv/www/postmaster/releases/20160601115602/application/controllers/task/Message.php(66): Lib_archive->send(Array)
#17 [internal function]: Message->send()
#18 /srv/www/postmaster/releases/20160601115602/system/core/CodeIgniter.php(514): call_user_func_array(Array, Array)
#19 /srv/www/postmaster/releases/20160601115602/index.php(299): require_once('/srv/www/postma...')
#20 {main}
)
```

**Comment by suvozit** [comment]
```
to_name 23467890-''"''4e5674rvb7y4r
```
